# Build
FROM maven:3.6.3-jdk-8-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

# Package
FROM openjdk:8-jre-slim
COPY --from=build /home/app/target/poller-0.0.1-SNAPSHOT.jar /usr/local/lib/poller.jar
ENTRYPOINT ["java","-jar","/usr/local/lib/poller.jar"]
